;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        delete-window
        indent-for-tab-command
        js-eval-defun
        kill-visual-line
        mouse-buffer-menu
        projectile-find-file
        projectile-switch-to-buffer
        switch-to-buffer
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        comment-dwim
        end-of-visual-line
        enlarge-window-horizontally
        geosoft-backward-word
        geosoft-forward-word
        ignore
        indent-region
        isearch-forward-word
        js2-indent-bounce
        js2-mode-show-element
        js2-mode-show-node
        kill-sentence
        mode-line-previous-buffer
        mouse-drag-mode-line
        mouse-select-window
        mouse-set-region
        mouse-set-secondary
        overwrite-mode
        projectile-find-file-dwim
        shrink-window-horizontally
        ))
